---

base_archiving_tools:
  - arj
  - cabextract
  - file-roller
  - mpack
  - p7zip-full
  - p7zip-rar
  - rar
  - sharutils
  - unace
  - unrar
  - unzip
  - uudeview
  - zip

base_productivity_tools:
  - libreoffice
  - zoom

base_system_tools:
  - clipit
  - fatrace
  - fdupes
  - gnome-calculator
  - gufw
  - openvpn
  - progress
  - pwgen
  - apt-transport-https
  - ca-certificates 
  - curl
  - software-properties-common
  #- syncthing

base_system_tools_laptop:
#  - cpufrequtils
#  - powertop
  - tlp
  - tlp-rdw
  - acpi-call-dkms  # for newer ThinkPads (X220/T420 and later)
#  - tp-smapi-dkms  # for older ThinkPads

base_download_tools:
  - aria2
  - axel
  - transmission
  - speedtest-cli
  - wget
  - youtube-dl

base_developer_tools:
  - 2to3
#  - android-tools-adb
#  - android-tools-fastboot
  - ansible
  - ansible-lint
  - awscli
  - bat
  - bpython
  - black
  - cloc
  - clusterssh
  - colordiff
  - csvkit
  - default-jre-headless
  - dos2unix
  - entr
  - expect
  - filezilla
  - fonts-powerline
  - fzf
  - g++
  - gedit-plugins
  - geoip-bin
  - ghostwriter
  - git
  - git-extras
  - gitg
  - golang-go
  - htop
  - httpie
  - inotify-tools
  - ipython3
  - jq
  - kitty
  - kwalify
  - makeself
  - meld
  - miller
  - moreutils
  - most
  - ncat
  - netcat
  - nmap
  - nmon
  - nodejs
  - pandoc
  - parallel
  - pep8
  - pipenv
  - powerline
  - pry
  - pssh
  #- puppet
  #- puppet-lint
  - php8.1
  - pv
  - pylint
  - python3-demjson  # provides jsonlint-py3 for json lint
  - python3-jmespath
  - python3-pep8
  - python3-pip
  - ranger
  - rclone
  - recode
  - remmina
  - rename
  - ripgrep  # launch using rg from the cli
  - ruby
  - ruby-dev
  - shellcheck
  - siege
  - socat
  - sshfs
  - sshpass
  - sshuttle
  - tilix
  - tldr
  - tmux
  - tmuxp
  - tree
  - uget
  - xclip
  - yamllint
  - zeal

base_virtualization_tools:
  - virtualbox
#  - virtualbox-ext-pack
  - docker.io
  - docker-compose

base_media_tools:
  - ffmpeg
  - gimp
  - imagemagick
  - libimage-exiftool-perl
  - mediainfo
  - soundconverter
  - totem
  - ubuntu-restricted-extras
  - vlc

base_permanent_night_light:
  night_light_enabled: False              # set this to True for permanently turning on night light
  night_light_schedule_automatic: False
  night_light_schedule_from: 0
  night_light_schedule_to: 24
  night_light_temperature: 4200

...
