---

- name: add docker apt key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_key_url }}"
    keyring: "{{ docker_apt_key_keyring }}"

- name: add docker repo for ubuntu 22.04
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo_jammy }}"
    state: present
    filename: docker
  when: ansible_distribution_release == "jammy"

- name: install docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    force_apt_get: yes

...
